import React from "react";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar";
import { ThemeProvider } from "@/components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Syed Adeeb",
	description: "Generated by create next app",
	icons: "/favicon.svg",
};

export default function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html
				lang="en"
				className=""
				suppressHydrationWarning
				suppressContentEditableWarning>
				<body className={`${inter.className}`}>
					<ThemeProvider attribute="class">
						<div className="overflow-x-hidden">{children}</div>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
