import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Syed Adeeb",
	description: "Generated by create next app",
	icons: "/favicon.svg",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="" suppressHydrationWarning>
			<body className={`${inter.className}`}>
				<ThemeProvider attribute="class">
					<NavBar />
					<>{children}</>
				</ThemeProvider>
			</body>
		</html>
	);
}
